_wandb:
    value:
        cli_version: 0.23.0
        e:
            7mrbe4ywufarm681h88idmzwj39vjzno:
                codePath: c:\Users\EG\OneDrive - ITU\Kandidat\3. semester\AML - Computer Vision\IMTL\Pipeline.ipynb
                codePathLocal: Pipeline.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "999527804928"
                        used: "887104122880"
                email: mfau@itu.dk
                executable: c:\Programming\Anaconda\envs\ml310\python.exe
                git:
                    commit: d1b6e39002f27aac5978799e9dd47a027abdeb08
                    remote: https://github.com/DanyalYor/IMTL.git
                gpu: NVIDIA GeForce RTX 2080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 3072
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2080 SUPER
                      uuid: GPU-b1eddb1c-9d10-a498-4a00-8198de6f7329
                host: DESKTOP-LB36RUV
                memory:
                    total: "34269880320"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\EG\OneDrive - ITU\Kandidat\3. semester\AML - Computer Vision\IMTL\Pipeline.ipynb
                python: CPython 3.10.19
                root: c:\Users\EG\OneDrive - ITU\Kandidat\3. semester\AML - Computer Vision\IMTL
                startedAt: "2025-12-02T11:14:06.242251Z"
                writerId: 7mrbe4ywufarm681h88idmzwj39vjzno
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 30
                - 41
                - 53
            "2":
                - 1
                - 5
                - 30
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.19
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
augmentation:
    value: AutoAugment_IMAGENET
batch_size:
    value: 32
feature_extractor_frozen:
    value: true
img_size:
    value: 224
learning_rate:
    value: 0.001
model_name:
    value: efficientnet_b0
num_classes:
    value: 101
optimizer:
    value: Adam
test_size:
    value: 1515
train_size:
    value: 7070
transfer_learning:
    value: true
val_size:
    value: 1515
