_wandb:
    value:
        cli_version: 0.23.0
        e:
            l29h6kj1onercjmpdscfbva3dpgx5dui:
                codePath: c:\Users\marku\OneDrive - ITU\Kandidat\3. semester\AML - Computer Vision\IMTL\Pipeline.ipynb
                codePathLocal: Pipeline.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1021821579264"
                        used: "944900898816"
                email: mfau@itu.dk
                executable: c:\Users\marku\anaconda3\envs\iml\python.exe
                git:
                    commit: 1c2153e267aa0f95ade6872edc75b21637ab19c6
                    remote: https://github.com/DanyalYor/IMTL.git
                gpu: NVIDIA GeForce RTX 3070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5120
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070 Laptop GPU
                      uuid: GPU-ef6f171b-0c19-a8cd-efd2-01c49cfa851b
                host: Markus
                memory:
                    total: "16312393728"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\marku\OneDrive - ITU\Kandidat\3. semester\AML - Computer Vision\IMTL\Pipeline.ipynb
                python: CPython 3.10.14
                root: c:\Users\marku\OneDrive - ITU\Kandidat\3. semester\AML - Computer Vision\IMTL
                startedAt: "2025-11-27T11:59:41.530561Z"
                writerId: l29h6kj1onercjmpdscfbva3dpgx5dui
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 30
                - 41
                - 53
            "2":
                - 1
                - 5
                - 30
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.10.14
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
augmentation:
    value: AutoAugment_IMAGENET
batch_size:
    value: 32
feature_extractor_frozen:
    value: true
img_size:
    value: 224
learning_rate:
    value: 0.001
model_name:
    value: efficientnet_b0
num_classes:
    value: 101
optimizer:
    value: Adam
test_size:
    value: 1515
train_size:
    value: 7070
transfer_learning:
    value: true
val_size:
    value: 1515
